### ISSUE TITLE
Wonderful timing!

### ISSUE THREAD

**Issue by technoplato** [deltaepsilon/firebase-ssr-starter#1]

**Comment by deltaepsilon** [comment]
I'm glad my content has been helpful! I don't often get feedback on it 👍 

I used this project as the seed for my most recent rewrite of Calligraphy.org. It contains a bunch of great ideas that I'll continue to use, but I don't intend to continue development on it.

Following the README should get you something functional. It's a sophisticated system, so I'd focus on understanding the way it builds on top of Next.js, Firebase and Docker. I ended up abandoning AMP; this isn't the right kind of project for AMP.

Good luck on your project! Platforms are wicked hard to build. I've given up on them and retreated to building single-purpose sites and games and whatever feels like fun. Someday I'll get VC funding and build something bigger :)

**Comment by technoplato** [comment]
Chris - I saw this was closed but didn't see you had responded. Thank you so much! 

I'm going to be looking through this eventually and maybe submitting some READMEs to make the content a little bit more explicit in each folder. Is that something you'd entertain the idea of merging? 

I find the individual pieces of this codebase by themselves quite simple, but will really have to dig in to figure out how each piece goes together, and figure others may feel the same. 

I'll be doing that shortly as I'm making some decent progress just hacking away. Finally gave in and started following red / green with Jest after watching your 'Cloud Functions the Easy Way' video. I don't actually need to test any cloud functions, but the idea of integration testing Firebase with Jest is fantastic. Going to really help me improve my productivity and focus, despite a little bit longer in setup.

I appreciate your well wishes! Again, I'll reiterate I've developed a revolutionary business model where I believe we'll be able to make you more money than with the current models of the middle man taking a cut of your profits. Obviously time will tell, but I'd love to 'buy you virtual lunch' to explain a little bit more about how that will work to see if you'd like to be a *pioneering* instructor on the platform. 

Thanks again for your response and I look forward to continuing to learn from your great work. You and Academind are by far my most favorite to learn from as you do a great job in explaining _complex_ quite simply, and that is a gift, so thank you very much for sharing.

**Comment by deltaepsilon** [comment]
@technoplato I love pull requests! I'm happy to merge improvements to the README or anything else you find.

Red/green testing with Jest is incredibly powerful. It can take a bit of extra time to set up, but you'll be thank for all of the time it saves once you get deep into Cloud Functions work.

My workload for the next few years is pretty well booked, but send me an email at chris@christopheresplin.com and let's talk business models :)

**Comment by technoplato** [comment]
You’re absolutely right about the setup. Took me a couple days to get everything working with debugging and async await with my next config but finally have things working and it’s quite refreshing to not have to worry about manually doing everything. 

The tests I’m writing are probably certainly not best practices and I can still learn a ton about writing CLEAN code, but I’d rather have a bunch of helpful tests written portly than none at all. Failure and improvement cycles are the best way to learn for me...

As for the business models, I’ll write the schpiel below and email you as well. Feel free to only respond to the email, I just am very passionate about creative openness and so in the off chance that someone comes across this issue, I want them to be able to read as well.

**Comment by technoplato** [comment]
# Knophy Explainers (all)
### Target: all
#knophy/explainer/all

Knophy is going to be many things to many people. The overarching philosophy of Knophy is to value competence in online communication. I plan to do that algorithmically and economically. Please let me know if you are interested in hearing more details about that particular mechanism. I need to touch on some small details from my business model, but won’t go until full detail in the interest of just getting to the point. Please, by all means, challenge me on this idea. I want it to be rock solid. 

I propose a business model where all content is free. Every video, text post, and sound clip is universally accessible to anyone with an internet connection (and eventually, even those without one through free global print publishing funded by this very model). There are no ads. There are no tasks you are required to perform. No information you must provide about yourself. Nada. Zilch. 

In that model, I also propose a way to earn points for demonstrating one’s competence on content. Put differently, the conversation surrounding content should consist largely of individuals that are discussing a common shared experience. The only way to ensure that happens is by imposing some limit. The only fair limit I can imagine is simply figuring out the answer to this question: "Did you consume the same content I just spent my attention consuming?" This is not how the internet functions today. The outrageous and the angry messages spread, drowning out those of human compassion and true community. The way to demonstrate competency and discourage the spread of those kinds of negative messages will be through taking community sourced and moderated quizzes within topic areas. Those questions will be sourced from the free content posted on the website. Evidence for correct answers MUST be objective and MUST be provided or a question is invalid.  Care will be taken to ensure statistically valid questions are curated. 

Answering questions correctly will earn the user points in that given topic area as well as gain them overall points site wide. Those points can be used to promote their own content within the topics in which they are earned, therefore increasing the influence of the demonstrably competent. 

This model will also have special topics which will allow the user to earn “power ups” for earning that will multiply the points earned in all categories. Some of these topics will include writings about the underlying philosophy of this system, the technological details, a book that I’m live writing, and eventually will serve as a compensation mechanism for open source work that is fair and perpetual and will reflect the impact a developer has made on the system. If there is a place where I stand to gain from this most, it is in the ability to use this system to promote my ideas. However, I will also eventually seek to have others (or myself time permitting) create tutorials to modify and build their own website like knophy. The code is always going to be open source (http://GitHub.com/Technoplato/knophy), as is the business itself. I believe this is a fair trade. Imagine if one of Facebook's core goals was to allow for one click deployment of their website where they stand to not benefit whatsoever except to free the user to do as she pleases. 

The prototype of the system will limit these topics to conscious individuals such as yourself, President Obama, President Trump, Lady Gaga, Jordan Peterson, etc. Content posted under that topic MUST contain their knowing participation in the first person. This kind of content will include speeches, interviews, debates, conversations, video recordings otherwise created, writings or any other content penned by their hand. This will form an [archive similar to this one for Steve Jobs](https://en.wikipedia.org/wiki/Timeline_of_Steve_Jobs_media). The content will be more well organized, queriable, and archived permanently. 

The quizzes mentioned above MUST provide evidence backed answers which will link to specific pieces of this first person content. Open source annotation engines will be highly useful. One that I've already discovered and begun using is called Hypothesis. 

Content that doesn’t meet those criteria will still be allowable, but in a different part of the website, where communities can discuss topics in the third person. You can think of these first person topics as one’s intimate creations rather than anything created ABOUT that person. Later, the concept of topics will be expanded to that resembling the sections in a newspaper. Special care will be taken in the grouping of these topics, as that grouping will directly effect who has the most influence in those areas. 

If the user prefers, she can sell her points on the market to investors, REMOVING COMPLETELY those points from EVER having any influence. An investor that buys points DOES NOT earn any influence in the topics whatsoever. This investment is simply that-an investment in the investor’s belief that this system is valuable and its value will increase over time. 

Investors will be able to invest in a particular topic’s growth, a collection of topics, or the overall growth of the system. 

Essentially, the product we are selling is a bet that people will value earning attention, ESPECIALLY as the platform grows. As it grows, each one of those points is held onto more tightly and becomes both harder to buy (caused by one's desire to earn attention) and easier to earn as the content base will grow exponentially. This perfect balance of the human's desire for attention, their ability to easily create and share in a digital age, and their desire for money will form the first purposefully scarce unlimited supply of currency in the history of humanity. The key is simply not allowing money to have influence in the system. 

The love of money is the root of all evil. 
Knowledge is incorruptible. 

Thank you for your time. If this hasn't piqued your interest, I'm afraid I have nothing more to offer and you should be on your merry way. 

If it has, please email me back or at lustig@knophy.com. I look forward to changing the world together. 

I need help from designers, developers, people interested in dogfooding and really anyone if you're interested in finding better ways of making humanity function together through technology. 

Yours in truth and knowledge,
Michael Lustig

Details I failed to include (listing them here to not throw off the flow of the explanation)
* When a question is answers on content that YOU create, you earn points as well as the question reviewers, the question submitter, and the answerer. You can use those points in exactly the same manner as if you earned then through quizzes. 
* Probably more but what can you do? Let me know if any questions and I will answer them. The prototype is currently being worked on and is love but doesn't do much of anything yet. I'm a thinker first, then a developer, and a shitty one at that. I need help from talented and passionate individuals.

**Comment by deltaepsilon** [comment]
I've written an awful lot of terrible code over the years. I've thrown away
almost all of the code that I've written on my own projects, even the
successful ones.

But every codebase has been better than the last, so as long as I'm making
progress, I'll get there one of these decades :)

I'm 7 years deep into this coding game, and I just now feel like I can make
and ship solid applications on my own. But that didn't stop me from making
money and providing tons of value in the early years... I just did it with
lousy code :)
